apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: timeserver-pod
    spec:
      containers:
      - name: timeserver-container
        image: us-central1-docker.pkg.dev/care-dataservice/test-artifact-repository/timeserver:1
        readlinessProbe:
          initialDelaySeconds: 15 
          periodSeconds: 30
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        livenessProbe: 
          initialDelaySeconds: 30
          periodSeconds: 30
          #Perform HTTP request every 30 secend. 
          #And consider 10 error responses in a row to indicate the container is not ready
          #And consider 1 successful response to indicate the container is ready after being considered unready
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 5
          failureThreshold: 10
          successThreshold: 1
