apiVersion: apps/v1
kind: Depoyment
metadata:
  name: timeserver
spec:
  replicas: 3
  selector: 
    matchLabels:
      pod: timeserver-pod
  template:
    metadata:
      labels:
        pod: timeserver-pod
    spec:
      containers:
      - name: timeserver-container
        image: us-central1-docker.pkg.dev/care-dataservice/test-artifact-repository/timeserver:1
        resources:
          #Resource requests for this deployment
          request:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 300m
            memory: 400Mi